variables:
  GIT_CLEAN_FLAGS: -n

stages:
  - development
  - release
  - production

cache:
  key: "${CI_PROJECT_ID}-${CI_COMMIT_REF_SLUG}"
  paths:
    - node_modules/
    
before_script:
  #- export http_proxy=http://192.168.13.6:3128
  #- export https_proxy=http://192.168.13.6:3128

after_script:
  - docker image prune -f
  - echo "done"

development:
  stage: development
  script:
    - docker-compose -f docker-compose.dev.yml up -d --force-recreate --build dev-sita
  tags:
    - development
  only:
    - development

release:
  stage: release
  script:
    - sed -i 's/development/testing/' app.json
    - docker-compose -f docker-compose.release.yml up -d --force-recreate --build release-sita
  tags:
    - release
  only:
    - release

production:
  stage: production
  script:
    # to set environtment production / testing
    - sed -i 's/development/production/' app.json
    - docker-compose -f docker-compose.prod.yml up -d --force-recreate --build prod-sita
  tags:
    - production
  only:
    - master