stages:
  - development
  - production

cache:
  paths:
    - node_modules/
    
before_script:
  #- export http_proxy=http://192.168.13.6:3128
  #- export https_proxy=http://192.168.13.6:3128

after_script:
  - docker image prune -f
  - echo "done"

development:
  stage: development
  script:
    - git-docker -c dev-sita -i gitlab.vascomm.co.id:4567/iot_ceria/sita_dev:latest_dev
  tags:
    - development
  only:
    - development

production:
  stage: production
  script:
    # to set environtment production / testing
    - sed -i 's/development/production/' app.json
    - docker-compose -f docker-compose.prod.yml build
    - docker-compose -f docker-compose.prod.yml up -d --force-recreate
  tags:
    - production
  only:
    - master