stages:
  - development
  - production

before_script:
  - export http_proxy=http://192.168.13.6:3128
  - export https_proxy=http://192.168.13.6:3128

after_script:
  - docker image prune -f
  - docker push gitlab.vascomm.co.id:4567/iot_ceria/sita_dev
  - echo "done"

development:
  stage: development
  script:
    - docker-compose -f docker-compose.dev.yml build
    - docker-compose -f docker-compose.dev.yml up -d --force-recreate
  tags:
    - development
  only:
    - sita_dev
production:
  stage: production
  script:
    - docker-compose -f docker-compose.prod.yml build
    - docker-compose -f docker-compose.prod.yml up -d --force-recreate
  tags:
    - production
  only:
    - master

