version: '3.7'

services:
  prod-sita:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # - ./:/usr/src/app
      # - /usr/src/app/node_modules
      - /home/apps/config_env/iot_ceria/sita_dev/.env:/usr/src/app/.env.production
      - /home/apps/logs_pm2:/usr/src/log
      # digunakan untuk backend cdn (simpan gambar)
      - /home/apps/cdn_image/sita_dev:/usr/src/app/public/cdn
    ports:
      - 5000:5000
      - 5005:5005
    tty: true
    container_name: prod-sita
    image: gitlab.vascomm.co.id:4567/iot_ceria/sita_dev:latest_prod
    networks:
      - vascomm-app
    restart: always

networks:
  vascomm-app:
    name: vascomm-app
    driver: bridge
